name: 'Auto Assign Action'

on:
  pull_request:
    types: [opened, ready_for_review, labeled, unlabeled]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Auto Assign
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          configuration-path: '.github/list_auto_assign.yml'
          repo-token: ${{ steps.generate_token.outputs.token }}

    permissions:
      contents: read
      pull-requests: write
