name: 'Pull Request Labeler'

on:
  pull_request:
    types: [opened, ready_for_review, labeled, unlabeled, reopened, synchronize]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Label PR
        uses: actions/labeler@v6
        with:
          repo-token: ${{ steps.generate_token.outputs.token }}
          # sync-labels: true (Opcional: elimina etiquetas si los archivos cambian)
