name: 'Update Submodule Action'
on:
  repository_dispatch:
    types: [update-submodules-famaf]
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SHOULD_COMMIT: ''

jobs:
  famaftestupdate:
    name: Update submodules
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          submodules: recursive
          fetch-depth: 0

      - name: Update submodules
        run: git submodule update --init --recursive --checkout -f --remote

      - name: Update status
        id: status
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "SHOULD_COMMIT=true" >> $GITHUB_ENV
          else
            echo "SHOULD_COMMIT=false" >> $GITHUB_ENV
          fi

      - name: Config git and Push
        if: ${{ env.SHOULD_COMMIT == 'true' }}
        run: |
          git config --global user.name "${{ steps.generate_token.outputs.app-slug }}[bot]"
          git config --global user.email "${{ steps.generate_token.outputs.app-user-id }}+${{ steps.generate_token.outputs.app-slug }}[bot]@users.noreply.github.com"

          # Ejecutar tu script de actualización
          source ./Famaf-Resources-Manager/scripts/update_w_from_parent.sh

          git add .
          git commit -m "[BOT] Update submodules at $(date "+%Y-%m-%d %H:%M:%S")"
          git push
